name: 'Deleting Resources'

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy all resources'
env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-west-1
  
jobs:
  destroy:
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      working-directory: module/
      run: terraform init
      env:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.region }}

      
      
    - name: Destroy Resources
      working-directory: module/
      run: terraform destroy -auto-approve
      env:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.region }}
      

      
